version: '3'
services:
  web:
    image: nginx:1.19
    ports:
      - '8000:80'
    depends_on:
      - app
    volumes:
      - ./docker/web/templates:/etc/nginx/templates
      - .:/var/www/html
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    environment:
      # アプリケーションの環境変数については ./laravel-app/.env.xxxx 参照
      DB_CONNECTION: mysql
      DB_READ_HOST: db
      DB_READ_PORT: 3306
      DB_READ_DATABASE: payke_template
      DB_READ_USERNAME: follower
      DB_READ_PASSWORD: 6Io^AkNzz5AuWb+x
      DB_WRITE_HOST: db
      DB_WRITE_PORT: 3306
      DB_WRITE_DATABASE: payke_template
      DB_WRITE_USERNAME: admin
      DB_WRITE_PASSWORD: VR*aT[f>wAn7m5u2
      REDIS_HOST: cache
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    depends_on:
      - db
    volumes:
      - ./laravel-app:/var/www/html
  db:
    build:
      context: ./docker/db
      args:
        MYSQL_DATABASE: payke_template
        MYSQL_REPLICA_USER: follower
        MYSQL_REPLICA_PASSWORD: 6Io^AkNzz5AuWb+x
    environment:
      MYSQL_ROOT_PASSWORD: _xwJL4<N_<ib5FP]
      MYSQL_DATABASE: payke_template
      MYSQL_USER: admin
      MYSQL_ROOT_HOST: 172.18.0.1
      MYSQL_PASSWORD: VR*aT[f>wAn7m5u2
      MYSQL_REPLICA_USER: follower
      MYSQL_REPLICA_PASSWORD: 6Io^AkNzz5AuWb+x
      TEST_DUMP_HOST: localhost
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  cache:
    image: redis:5.0.8
    ports:
      - 6379:6379
    volumes:
      - cache-data:/data

volumes:
  db-data:
    driver: local
  cache-data:
    driver: local
